---
title: "GenerativeArt Examples"
author: "Aiden Kelly, Brandon Kim, Sam Todd"
format: 
  html:
    self-contained: true
    code-tools: true
    code-overflow: wrap
    toc: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

# Setup

## Load Packages

```{r}
library(GenerativeArt)
```

# Examples

## **canvasca** - Cellular Automation

### Setup

```{r}
myColors <- c("#9D7161", "#0C2C3C")
```

### My Cellular Automation Algorithm

```{r}
GenerativeArt::canvasca(myColors, n = 150, iterations = 30, probability = 0.35)
```

## Conway's Game of Life Algorithm

```{r}
GenerativeArt::canvasca(myColors, n = 200, iterations = 40, probability = 0.65, conway = TRUE)
```

## **canvasknn** - K Nearest Neighbors

```{r}
GenerativeArt::canvasknn(myColors, k = 5, n = 100, resolution = 10, rbinom, size = 30, prob = 0.5)
```

## **canvaslogreg** - Logistic Regression

```{r}
GenerativeArt::canvaslogreg(color1 = myColors[1], color2 = myColors[2], n = 500, resolution = 500, rexp, rate = 3)
```

## **canvastree** - Decision Tree

```{r}
GenerativeArt::canvastree(myColors, n = 100, resolution = 100, runif, 0, 100)
```
